name: compass-runtime-agent
on:
  push:
    branches: [ main ]

  pull_request_target:
    branches: [ main ]
    paths:
      - 'application-connector.yaml'
      - 'application-connector-dependencies.yaml'
      - 'tests/Makefile'
      - 'tests/Dockerfile.compass-runtime-agent'
      - 'tests/Makefile.test-compass-runtime-agent'
      - 'tests/go.mod'
      - 'tests/go.sum'
      - 'tests/hack/**'
      - 'tests/internal/testkit/**'
      - 'tests/resources/charts/compass-runtime-agent-test/**'
      - 'tests/scripts/fetch-test-logs.sh'
      - 'tests/scripts/generate-self-signed-certs.sh'
      - 'tests/scripts/jobguard.sh'
      - 'tests/scripts/local-build.sh'
      - 'tests/test/compass-runtime-agent'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  reuse:
    # we're using reusable because we can't modify workflows as contributors
    # it could cause the secret leakeages
    uses: "./.github/workflows/reusable-k3d-agent-test.yml"
    with:
      k3d-version: v5.6.0
    secrets:
      compass-host: ${{ secrets.COMPASS_HOST }}
      compass-client-id: ${{ secrets.COMPASS_CLIENT_ID }}
      compass-client-secret: ${{ secrets.COMPASS_CLIENT_SECRET }}
