name: app-con-validator
on:
  push:
    branches: [ main ]

  pull_request:
    paths:
      - 'tests/Makefile'
      - 'tests/Dockerfile.connectivity-validator'
      - 'tests/go.mod'
      - 'tests/go.sum'
      - 'tests/hack/**'
      - 'tests/internal/testkit/httpd/**'
      - 'tests/resources/charts/application-connectivity-validator-test/**'
      - 'tests/scripts/fetch-test-logs.sh'
      - 'tests/test/application-connectivity-validator/**'

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/setup-helm@v4.1.0
        id: install

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up go environment
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2

      - name: Install k3d
        env:
          K3D_URL: https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh
          DEFAULT_K3D_VERSION: v5.6.0
        run: curl --silent --fail $K3D_URL | TAG=$DEFAULT_K3D_VERSION bash

      - name: Insall yq
        run: sudo add-apt-repository ppa:rmescandon/yq && sudo apt update && sudo apt install yq -y

      - name: Run unit tests
        run: make -C tests/hack/ci k3d-validator-tests

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: application-connectivity-validator-test-results
          path: application-connectivity-validator-test.log

      - name: Create summary
        if: always()
        run: |
          echo \`\`\` >> $GITHUB_STEP_SUMMARY
          cat application-connectivity-validator-test.log >> $GITHUB_STEP_SUMMARY
          echo \`\`\` >> $GITHUB_STEP_SUMMARY
