name: module

on:
  push:
    branches: [ "main" ]

  pull_request:
    paths:
      - 'Dockerfile'
      - 'Makefile'
      - 'api/**'
      - 'application-connector-dependencies.yaml'
      - 'application-connector.yaml'
      - 'config/**'
      - 'controllers/**'
      - 'go.mod'
      - 'go.sum'
      - 'hack/**'
      - 'main.go'
      - 'pkg/**'
      - '!test/**'

permissions:
  contents: read

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up go environment
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.2

    - name: Run integration tests without lifecycle-manager
      run: make -C hack/ci run-without-lifecycle-manager

  unit-tests:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up go environment
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.2

    - name: Run unit tests
      run: make test

